name: fact_or_fiction_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - numpy=1.25.2
  - matplotlib=3.5.3
  - pandas=2.2.2
  - pytorch=2.0.1
  - scikit-learn=1.4.2
  - nltk=3.8.1
  - pip 
  - pip:
    - transformers==4.40.2
    - spacy==3.7.4
    - torch-geometric==2.5.3